### ISSUE TITLE
 Argument 1 passed to Swift_Mailer::send() must implement interface Swift_Mime_Message, instance of YiiMailMessage given,

### ISSUE THREAD

**Issue by GoogleCodeExporter** [emmanuelgautier/yii-mail#17]
```
I have "all" PHP warnings/errors active (in the PHP.INI)


I get the following error:

PHP Error[4096]: Argument 1 passed to Swift_Mailer::send() must implement 
interface Swift_Mime_Message, instance of YiiMailMessage given, called in 
D:\workspace\project\protected\extensions\yii-mail\YiiMail.php on line 181 and 
defined
    in file D:\workspace\project\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php at line 68


#0 D:\workspace\project\protected\extensions\yii-mail\YiiMail.php(181): 
Swift_Mailer->send()
#1 D:\workspace\project\protected\commands\CheckAlertsCommand.php(181): 
YiiMail->sendSimple()
#2 D:\workspace\project\protected\commands\CheckAlertsCommand.php(159): 
CheckAlertsCommand->notifyAlert()
#3 D:\workspace\project\protected\commands\CheckAlertsCommand.php(119): 
CheckAlertsCommand->checkMouvementAlert()
#4 D:\workspace\project\protected\commands\CheckAlertsCommand.php(16): 
CheckAlertsCommand->checkPositions()
#5 D:\workspace\yii\framework\console\CConsoleCommandRunner.php(65): 
CheckAlertsCommand->run()
#6 D:\workspace\yii\framework\console\CConsoleApplication.php(91): 
CConsoleCommandRunner->run()
#7 D:\workspace\yii\framework\base\CApplication.php(162): 
CConsoleApplication->processRequest()
#8 D:\workspace\yii\framework\yiic.php(33): CConsoleApplication->run()
#9 D:\workspace\project\protected\yiic.php(7): require_once()

This happens with a 'sendSimple' as well as the advanced example.

```

Original issue reported on code.google.com by `Mario.De...@gmail.com` on 10 May 2012 at 11:55

**Comment by ChristianTheMinery** [comment]
Having this same issue.

**Comment by emmanuelgautier** [comment]
Sorry but the package is not maintained anymore. You are free to make a pull request to fix it.
